name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code
        run: echo "Linting Repository"

      - name: Run Unit Tests
        run: echo "Running Unit Tests"

  build-and-push-ecr-image:
    name: Continuos Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run:
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure Docker Credentials
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image to Dockerhub
        run:
          docker build -t ${{ secrets.DOCKER_USERNAME }}/elephant-detection:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/elephant-detection:latest
    